- name: configure catalogue component
  hosts: catalogue
  become: yes
  tasks:
  - name: disabling default nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enabling default nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: installing nodejs:20
    ansible.builtin.dnf:
     name: nodejs
     state: present

  - name: creating roboshop user
    ansible.builtin.user:
     name: roboshop
     shell: /sbin/nologin
     system: true
     home: /app
   
  - name : creating app directory
    ansible.builtin.file:
     path: /app
     state: directory

  - name: downloading catalogue code
    ansible.builtin.get_url:
     url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
     dest: /tmp/catalogue.zip

  - name: extrating code from zip file
    ansible.builtin.unarchive:
     src: /tmp/catalogue.zip
     dest: /app
     remote_src: yes

  - name: downloading dependies
    community.general.npm:
     path: /app

  - name: copying catalogue service into system service
    ansible.builtin.copy:
     src: catalogue.service
     dest: /etc/systemd/system/catalogue.service

  - name: daemon-reload
    ansible.builtin.systemd_service:
     daemon_reload: true

  - name : starting and enabling service
    ansible.builtin.service:
     name: catalogue
     state: started
     enabled: yes

  - name: copying mongoclient
    ansible.builtin.copy:
     src: mongo.repo
     dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.dnf:
     name: mongodb-mongosh
     state: present

  - name: check products loaded or not
    ansible.builtin.command: mongosh --host mongodb.daws84s.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output

  - name: print catalogue output
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"

  - name: load products
    ansible.builtin.shell: mongosh --host mongodb.daws84s.site < /app/db/master-data.js
    when: catalogue_output.stdout | int < 0

    


  



