- name: configure cart component
  hosts: cart
  become: yes
  tasks:
  - name: disabling default nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enabling default nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: installing nodejs:20
    ansible.builtin.dnf:
     name: nodejs
     state: present

  - name: creating roboshop cart
    ansible.builtin.user:
     name: roboshop
     shell: /sbin/nologin
     system: true
     home: /app
   
  - name : creating app directory
    ansible.builtin.file:
     path: /app
     state: directory

  - name: downloading cart code
    ansible.builtin.get_url:
     url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip 
     dest: /tmp/cart.zip

  - name: extrating code from zip file
    ansible.builtin.unarchive:
     src: /tmp/cart.zip
     dest: /app
     remote_src: yes

  - name: downloading dependies
    community.general.npm:
     path: /app

  - name: copying cart service into system service
    ansible.builtin.copy:
     src: cart.service
     dest: /etc/systemd/system/cart.service

  - name: daemon-reload
    ansible.builtin.systemd_service:
     daemon_reload: true

  - name : starting and enabling service
    ansible.builtin.service:
     name: cart
     state: started
     enabled: yes

  