- name: configure shipping
  hosts: shipping
  become: yes
  tasks:
  - name: installing maven
    ansible.builtin.dnf:
     name: maven
     state: installed

  - name: creating roboshop user
    ansible.builtin.user:
     name: roboshop
     shell: /sbin/nologin
     system: true
     home: /app
   
  - name : creating app directory
    ansible.builtin.file:
     path: /app
     state: directory

  - name: downloading shipping code
    ansible.builtin.get_url:
     url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip 
     dest: /tmp/shipping.zip

  - name: extrating code from zip file
    ansible.builtin.unarchive:
     src: /tmp/shipping.zip
     dest: /app
     remote_src: yes   

  - name: install maven dependies
    ansible.builtin.command: mvn clean package
    args:
     chgir: /app

  - name: renanme jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
     chgir: /app
    

  - name: copying shipping service
    ansible.builtin.copy:
     src: shipping.service
     dest: /etc/systemd/system/shipping.service

  - name: daemon-reload
    ansible.builtin.systemd_service:
     daemon_reload: true

  - name: enable and start shipping
    ansible.builtin.service:
     name: shipping
     state: started
     enabled: yes
  
  - name : install mysql client
    ansible.builtin.dnf:
     name: mysql
     state: installed

  - name: import data
    tags:
    - import
    community.mysql.mysql_db:
      name: all
      login_user: root
      login_password: RoboShop@1
      login_host: mysql.ajay6.space
      state: import
      target: "{{ item }}"
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql
    - /app/db/master-data.sql

  - name: restart shipping
    tags:
    - import
    ansible.builtin.service:
      state: restarted
      name: shipping